version: "3"
services:
  riteshop-be:
    container_name: riteshop-be
    image: riteshop-be
    networks:
      - webnet
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      REDIS_HOST: redis
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - /src/node_modules

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - webnet
    env_file:
      - .env.development
    ports:
      - '27018:27017'
  redis:
    container_name: redis
    image: redis:7.0-alpine
    networks:
      - webnet
    expose:
      - 6379
    restart: unless-stopped
    ports:
      - '6379:6379'
networks:
  webnet: