# This is a basic workflow that is manually triggered

on:
  push:
    branches:
      - main
      - master
permissions:
  contents: write

name: Code Coverage

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: codecov/codecov-action@v3
    - name: Upload coverage reports to Codecov
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
